### ISSUE TITLE
general-todo

### ISSUE THREAD

**Issue by kurz-m** [kurz-m/transcendence#40]
### Frontend
- [x] #41
- [x] testcase
- [x] ~API calls for friends~
- [x] API calls for match history
- [x] #48
- [x] #43
- [x] #93
- [x] #51
- [x] #44
- [x] #59
- [x] #61
- [x] #60 
- [x] #67
- [x] #102
- [x] #115

### Backend
- [x] #73
- [x] #62 
- [x] #75
- [x] ~#80~
- [x] #81
- [x] #84
- [x] #86
- [x] #100
- [x] #111
- [x] #113
- [x] #114
- [x] #119

### Server
- [x] #95

### Docker
- [x] #82

### Monitoring
- [x] Implement Prometheus container
- [x] Implement Grafana container
- [x] Implement Cadvisor container
- [x] #70
- [x] #77
- [x] #99

### Logging

- [x] #89
- [x] #109

### BUGS
- [x] ~bugfix when removing volume and cookies are still there~
- [x] ~bugfix when using back button from tournament~
